### ISSUE TITLE
Add preview to knit engine

### ISSUE THREAD

**Issue by rkrug** [rkrug/plantuml#14]
It should be relatively easy, to add an inline preview to the knit engine, as the resulting file only needs to be printed to a graphics device? 

Based I=on a question from @retorquere

**Comment by rkrug** [comment]
Done in https://github.com/rkrug/plantuml/commit/dacde08118ca85d6cfc9c86ee855a2a0304d3508

**Comment by rkrug** [comment]
@retorquere Now you have an inline preview when you set `plantuml.preview = TRUE`

**Comment by retorquere** [comment]
Is this on master or on dev?

**Comment by rkrug** [comment]
On master. I merged it from dev.

**Comment by retorquere** [comment]
This is going to sound dumb, but beyond adding `plantuml.preview = TRUE`, what should I do? Or where should I see the preview?

**Comment by rkrug** [comment]
You have to run the code block in RStudio. There is a little triangle on the right of the beginning of the code block - clicking it will run the code and the graph will be shown below the code.

**Comment by retorquere** [comment]
I must not have upgraded properly then -- I did that and I just see the path of the image file.

**Comment by retorquere** [comment]
I've reinstalled the package, but no dice -- what am I doing wrong here: https://gist.github.com/b76fe910922ec31ba668f6f9c1386c45

**Comment by rkrug** [comment]
Hm. Works for me:

<img width="1922" alt="Screenshot 2020-06-23 at 14 13 20" src="https://user-images.githubusercontent.com/487172/85402337-c7629700-b55b-11ea-96d2-3530c6abd13d.png">

**Comment by retorquere** [comment]
I've removed and reinstalled plantuml, I've cleared my environment, but it doesn't show up for me.
