### ISSUE TITLE
cache output of plantuml knitr engine

### ISSUE THREAD

**Issue by retorquere** [rkrug/plantuml#15]
In the case of something like

````
```{plantuml name, plantuml.path="images"}
...
```
````

it should in principle be possible to hash the input and check if it has changed if the generated image could have the hash attached to it somehow (maybe in the metadata? filename would mean it would be harder to clean up)

**Comment by rkrug** [comment]
Knitr already implements a cache. 

Please check https://yihui.org/knitr/demo/cache/ - it should in theory work (I hope).

**Comment by rkrug** [comment]
I tried it once, and I think it worked, but I think I did have `plantuml.preview = FALSE`.

**Comment by rkrug** [comment]
Could yo please check with  `plantuml.preview = FALSE` and report back? Thanks.

**Comment by retorquere** [comment]
I have tried it with preview off -- it is a little faster, maybe? It's hard to actually tell, it's certainly not skipping all work. I still only see the same files in my cache directory also.

**Comment by rkrug** [comment]
Thanks - I will look into this. For the moment, I have no answer on the why and how.

**Comment by rkrug** [comment]
Needs to be checked with 0.6.5 onwards.
