### ISSUE TITLE
Error in if (options$eval) { : argument is not interpretable as logical

### ISSUE THREAD

**Issue by retorquere** [rkrug/plantuml#16]
With this: https://gist.github.com/6e2b5fa49b481189fb2668c28dd28fb0

I'm getting the error

```
Error in if (options$eval) { : argument is not interpretable as logical
```

if I just try to run the chunk. Knitting works OK.

**Comment by rkrug** [comment]
Thanks. For the moment, setting the default values in the setup chunk to eval = TRUE should do the job. Please leave this issue open as I would like to follow this up.

**Comment by rkrug** [comment]
Looked at it again and set the default `plantuml.format` to `"auto"`. But I assume, the initial cause of the error was already solved in an earlier release. 

The registration of the knit engine is done automatically now.
