### ISSUE TITLE
set options .onLoad rather than .onAttach ?

### ISSUE THREAD

**Issue by moodymudskipper** [rkrug/plantuml#22]
We get some errors when using plantuml without attaching because options are set only .onAttach and are required.

https://github.com/rkrug/plantuml/blob/master/R/aaa.R

It would be solved by setting options .onLoad, or by adapting the code that uses options to work when options are not set, .e.g. `plantuml_update()` calls `dir.exists(getPlantumlOption("jar_path")`.

**Comment by rkrug** [comment]
Sounds linke a good Suggestion. Please feel free to submit a pull request. Would be fastest. 

Thanks

**Comment by moodymudskipper** [comment]
Thanks and done :).
